server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_HOST:localhost}:${REGISTER_PORT:8761}/eureka/

  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: "classpath:db.changelog/changelog.sql"
    drop-first: true

  kafka:
    service: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
