server:
  port: ${GATEWAY_PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_HOST:localhost}:${REGISTER_PORT:8761}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/main/test/**
