server:
  port: 8080

register:
  hostname: localhost
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://${register.hostname}:${register.port}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service: true
      routes:
        - id: orders-get
          uri: lb://orders
          predicates:
            - Path: /test1
              Method: GET
