spring:
  datasource:
    url: "jdbc:postgresql://db-tickets:5432/postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

app:
  kafka:
    from-orders-id: "from-orders"

    orders-tickets-topic: "orders-to-tickets"
    tickets-orders-topic: "tickets-to-orders"
